TF-IDF

Formula:
1. Document Frequency(DF) = Number of times term t is present in all docs

2.Inverse Document Frequency (IDF(t)) = Total Documents / Number of documents term t is present in

3. IDF(t) = log(Total Documents / Number of documents term t is present in)

Ex: that->4/3 = 1.33

4. Term frequency (TF(t,d)) = (Total Number of time term t is present in doc A / Total number of tokens in doc A)

5. TF-IDF = TF(t,d) * IDF(t)

Limitations of the TF-IDF:

1. As n increased, dimensionality, sparcity also increses.
2. Doesn't address out of vocabulary problem.
3. Doesn't capture relationship between words

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
corpus = [
    "Thor eating pizza,Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface laptop tomorrow",
    "Amazon is announcing new echo-dot tomorrow",
    "I am eating biryani and you are eating grapes",
    "something is amazing"
    
]

In [ ]:
v = TfidfVectorizer() #Instance of the vectorizer
transformed_output = v.fit_transform(corpus)
print(v.vocabulary_)

{'thor': 28, 'eating': 11, 'pizza': 24, 'loki': 19, 'is': 17, 'ironman': 16, 'ate': 8, 'already': 0, 'apple': 6, 'announcing': 5, 'new': 22, 'iphone': 15, 'tomorrow': 29, 'tesla': 27, 'model': 21, 'google': 13, 'pixel': 23, 'microsoft': 20, 'surface': 26, 'laptop': 18, 'amazon': 3, 'echo': 12, 'dot': 10, 'am': 1, 'biryani': 9, 'and': 4, 'you': 30, 'are': 7, 'grapes': 14, 'something': 25, 'amazing': 2}

In [8]:
v.get_feature_names_out()

array(['already', 'am', 'amazing', 'amazon', 'and', 'announcing', 'apple',
       'are', 'ate', 'biryani', 'dot', 'eating', 'echo', 'google',
       'grapes', 'iphone', 'ironman', 'is', 'laptop', 'loki', 'microsoft',
       'model', 'new', 'pixel', 'pizza', 'something', 'surface', 'tesla',
       'thor', 'tomorrow', 'you'], dtype=object)

In [9]:
all_feature_names = v.get_feature_names_out()

for word in all_feature_names:
    indx = v.vocabulary_.get(word)
    print(f"{word} : {transformed_output[0,indx]}")

already : 0.24247316796912544
am : 0.0
amazing : 0.0
amazon : 0.0
and : 0.0
announcing : 0.0
apple : 0.0
are : 0.0
ate : 0.24247316796912544
biryani : 0.0
dot : 0.0
eating : 0.40642287704636554
echo : 0.0
google : 0.0
grapes : 0.0
iphone : 0.0
ironman : 0.24247316796912544
is : 0.10823642835747559
laptop : 0.0
loki : 0.24247316796912544
microsoft : 0.0
model : 0.0
new : 0.0
pixel : 0.0
pizza : 0.7274195039073762
something : 0.0
surface : 0.0
tesla : 0.0
thor : 0.24247316796912544
tomorrow : 0.0
you : 0.0

In [10]:
corpus[:2]

['Thor eating pizza,Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

In [11]:
transformed_output.toarray()[:2]

array([[0.24247317, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.24247317, 0.        ,
        0.        , 0.40642288, 0.        , 0.        , 0.        ,
        0.        , 0.24247317, 0.10823643, 0.        , 0.24247317,
        0.        , 0.        , 0.        , 0.        , 0.7274195 ,
        0.        , 0.        , 0.        , 0.24247317, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.31652498, 0.5639436 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.5639436 , 0.        , 0.25173606, 0.        , 0.        ,
        0.        , 0.        , 0.31652498, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.31652498,
        0.        ]])

Classify the goods into their types from the dataset

In [25]:
import pandas as pd

df = pd.read_csv("ecommerceDataset.csv")
print(df.shape)
df.head()

(50424, 2)

,Household,"Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room."
0,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ..."
1,Household,SAF 'UV Textured Modern Art Print Framed' Pain...
2,Household,"SAF Flower Print Framed Painting (Synthetic, 1..."
3,Household,Incredible Gifts India Wooden Happy Birthday U...
4,Household,Pitaara Box Romantic Venice Canvas Painting 6m...

In [26]:
df.columns = ['Label','Text']
df.head()

       Label                                               Text
0  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
2  Household  SAF Flower Print Framed Painting (Synthetic, 1...
3  Household  Incredible Gifts India Wooden Happy Birthday U...
4  Household  Pitaara Box Romantic Venice Canvas Painting 6m...

In [27]:
df.Label.value_counts()

Label
Household                 19312
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

In [29]:
from sklearn.utils import resample

min_count = df['Label'].value_counts().min()

df_balanced = pd.concat([
    resample(group, replace=False, n_samples=min_count, random_state=42)
    for label, group in df.groupby('Label')
])

In [31]:
df_balanced.Label.value_counts()

Label
Books                     8671
Clothing & Accessories    8671
Electronics               8671
Household                 8671
Name: count, dtype: int64

In [37]:
#Add the new column which gives a unique number to each of these labels 

df_balanced['label_num'] = df_balanced['Label'].map({
    'Household' : 0, 
    'Books': 1, 
    'Electronics': 2, 
    'Clothing & Accessories': 3
})

#checking the results 
df_balanced.head(5)

       Label                                               Text  label_num
27478  Books  L'Eschole Francoise: Pour Apprendre A Bien Par...          1
20212  Books  Organic Shastra Pav Bhaji Masala 150g Pav bhaj...          1
27384  Books  The Great War for Civilisation: The Conquest o...          1
21807  Books  MHT-CET 20 Question Paper Set (Physics, Chemis...          1
22125  Books  GROUP-1 MAINS APPSC-(Science & Technology,Envi...          1

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_balanced['Text'], df_balanced['label_num'], test_size=0.2, random_state=2022, stratify = df_balanced['label_num'])

In [43]:
mask = X_train.notna()
X_train = X_train[mask]
y_train = y_train[mask]

In [44]:
mask = X_test.notna()
X_test = X_test[mask]
y_test = y_test[mask]

In [45]:
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (27746,)
Shape of X_test: (6937,)
Shape of y_train: (27746,)
Shape of y_test: (6937,)

In [46]:
y_train.value_counts()

label_num
0    6937
2    6937
1    6936
3    6936
Name: count, dtype: int64

In [47]:
y_test.value_counts()

label_num
1    1735
0    1734
2    1734
3    1734
Name: count, dtype: int64

In [48]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

clf = Pipeline([
    ('vectorizer_tfidf', TfidfVectorizer()),
    ('KNN', KNeighborsClassifier())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1734
           1       0.96      0.95      0.96      1735
           2       0.94      0.95      0.95      1734
           3       0.97      0.98      0.98      1734

    accuracy                           0.96      6937
   macro avg       0.96      0.96      0.96      6937
weighted avg       0.96      0.96      0.96      6937

In [49]:
X_test[:5]

21318    Istanbul: Memories and the City (Vintage Inter...
1713     Cello Infiniti Mini 1 Net Storage Cabinet, Bro...
40918    ANDTRONICS Esynic 3.5" USB External Floppy Dis...
43599    LG 22 inch (55cm) LCD Monitor - Full HD, IPS P...
11072    Plantex Heavy Stainless Steel Mortar and Pestl...
Name: Text, dtype: object

In [52]:
X_test[:5][1713]

'Cello Infiniti Mini 1 Net Storage Cabinet, Brown Size:1 Storage                                                                                \xa0|\xa0                           Style:Net                                                                                \xa0|\xa0                           Color:Brown   Cello Infiniti wardrobes represent the ideals of cutting excess, practicality and an absence of decoration. Arrange your essentials in the most organized manner and plan your space in your own way. The Infiniti series is available in colours and can change the appearance and the mood of the room, needs minimum maintenance and you can simply assemble the product by followings steps shared in the user manual and hence cut down on professional installation cost. It is harmless as generally these furniture do not have any sharp corners and very light in weight. So, it is very safe where children are around. It is definitely going to be the most treasured possession. Modern furniture reflects the design philosophy of form following function prevalent in modernism. These designs represent the ideals of cutting excess, practicality and an absence of decoration. The forms of furniture are visually light (like in the use of polished metal and engineered wood) and follow minimalist principles of design which are influenced by architectural concepts like the cantilever. Modern furniture fits best in open floor plans with clean lines that thrive in the absence of clutter.'

In [50]:
y_test[:5]

21318    1
1713     0
40918    2
43599    2
11072    0
Name: label_num, dtype: int64

In [51]:
y_pred[:5]

array([1, 0, 2, 2, 0])

In [54]:
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('vectorizer_tfidf', TfidfVectorizer()),
    ('Multi NB', MultinomialNB())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93      1734
           1       0.97      0.92      0.95      1735
           2       0.94      0.95      0.95      1734
           3       0.97      0.98      0.98      1734

    accuracy                           0.95      6937
   macro avg       0.95      0.95      0.95      6937
weighted avg       0.95      0.95      0.95      6937

In [56]:
from sklearn.ensemble import RandomForestClassifier

clf = Pipeline([
    ('vectorizer_tfidf', TfidfVectorizer()),
    ('Random Forest', RandomForestClassifier())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1734
           1       0.97      0.96      0.97      1735
           2       0.97      0.95      0.96      1734
           3       0.98      0.98      0.98      1734

    accuracy                           0.96      6937
   macro avg       0.96      0.96      0.96      6937
weighted avg       0.96      0.96      0.96      6937

In [57]:
import spacy

nlp = spacy.load("en_core_web_sm")

def preprocess(text):
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
        
    return " ".join(filtered_tokens)

In [61]:
print(df_balanced['Text'].isna().sum())

0

In [60]:
df_balanced['Text'] = df_balanced['Text'].fillna("")

In [62]:
df_balanced['preprocessed_text'] = df_balanced['Text'].apply(preprocess)

In [ ]:
df_balanced.head()

In [ ]:
df_balanced.Text[0]

In [ ]:
df_balanced.preprocessed_text[0]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_balanced.preprocessed_text, df_balanced['label_num'], test_size=0.2, random_state=2022, stratify = df_balanced['label_num'])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf = Pipeline([
    ('vectorizer_tfidf', TfidfVectorizer()),
    ('Random Forest', RandomForestClassifier())
])

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))