In [1]:
import pandas as pd
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df.drop(['PassengerId', 'Name','SibSp','Parch', 'Ticket', 'Cabin','Embarked'], axis = 1, inplace = True)

In [3]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
target = df.Survived
input = df.drop('Survived', axis = 1)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
input['gender'] = le.fit_transform(input['Sex'], drop_first=True)

TypeError: LabelEncoder.fit_transform() got an unexpected keyword argument 'drop_first'

In [6]:
#inputs = pd.concat([input, dummies], axis = 'columns')
input.head()

   Pclass     Sex   Age     Fare  gender
0       3    male  22.0   7.2500       1
1       1  female  38.0  71.2833       0
2       3  female  26.0   7.9250       0
3       1  female  35.0  53.1000       0
4       3    male  35.0   8.0500       1

In [7]:
input.columns[input.isna().any()]

Index(['Age'], dtype='object')

In [8]:
input.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [10]:
input.Age = input.Age.fillna(input.Age.mean())
input.head(7)

   Pclass     Sex        Age     Fare  gender
0       3    male  22.000000   7.2500       1
1       1  female  38.000000  71.2833       0
2       3  female  26.000000   7.9250       0
3       1  female  35.000000  53.1000       0
4       3    male  35.000000   8.0500       1
5       3    male  29.699118   8.4583       1
6       1    male  54.000000  51.8625       1

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input,target, test_size = 0.2)

In [12]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'female'